version: '3.8'

services:
  kafka1:
    image: apache/kafka:3.7.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9092:9092  # Внутренний порт
      - 19092:19092 # Внешний порт
      - 9093:9093  # CONTROLLER (для KRaft)
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:19092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9095,3@kafka3:9097
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
    volumes:
      - ./kafka-data/kafka1-logs:/tmp/kraft-combined-logs
    networks:
      - kafka-net

  kafka2:
    image: apache/kafka:3.7.0
    container_name: kafka2
    hostname: kafka2
    ports:
      - 9094:9094  # Внутренний порт
      - 19094:19094 # Внешний порт
      - 9095:9095  # CONTROLLER (для KRaft)
    environment:
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9095,PLAINTEXT_HOST://:19094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9094,PLAINTEXT_HOST://localhost:19094
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9095,3@kafka3:9097
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
    volumes:
      - ./kafka-data/kafka2-logs:/tmp/kraft-combined-logs
    networks:
      - kafka-net
    depends_on:
      - kafka1

  kafka3:
    image: apache/kafka:3.7.0
    container_name: kafka3
    hostname: kafka3
    ports:
      - 9096:9096  # Внутренний порт
      - 19096:19096 # Внешний порт
      - 9097:9097  # CONTROLLER (для KRaft)
    environment:
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9096,CONTROLLER://:9097,PLAINTEXT_HOST://:19096
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9096,PLAINTEXT_HOST://localhost:19096
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9095,3@kafka3:9097
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
    volumes:
      - ./kafka-data/kafka3-logs:/tmp/kraft-combined-logs
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - kafka2

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9020:8080
    environment:
      AUTH_TYPE: DISABLED
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9094,kafka3:9096
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
     - 6379:6379
    volumes:
      - ./redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true


networks:
  kafka-net:
    driver: bridge

volumes:
  redis-data: